### ISSUE TITLE
Seems like 0.10.0 vertx.deployVerticle options parameter is not working

### ISSUE THREAD

**Issue by chengenzhao** [reactiverse/es4x#260] opened 2019-11-23 15:06 UTC
src/main/javascript/verticle.js
```javascript
var options = {
  "instances" : 1
};
console.log(options);
vertx.deployVerticle('Test', options);
```
src/main/java/Test.java
```java
import io.vertx.core.AbstractVerticle;

public class Test extends AbstractVerticle {
  public void start() {
    System.out.println(config());

    vertx.createHttpServer().requestHandler(req -> {
      req.response()
        .putHeader("content-type", "text/plain")
        .end("Hello from Vert.x!");
    }).listen(8080);
  }
}
```

then pack into fat jar and run it
I got an error:

> Unhandled exception caused by java.lang.UnsupportedOperationException: Unsupported operation identifier 'handle' and  object '{instances: 1}'(language: JavaScript, type: Object). Identifier is not executable or instantiable.

if we don't place options then it works nicely

**Comment by pmlopes** [comment] 2019-11-24 08:47
It looks like Graal is picking the wrong overload method. If you add a callback to the end of the call it might work (i haven't test it).

**Comment by chengenzhao** [comment] 2019-11-24 09:07
Nah, still got exceptions, and the code has been changed to 
```javascript
var options = {
  "instances" : 1
};
console.log(options);
vertx.deployVerticle('Test', options, function(res, err){});
```
got the error below, and if we remove options parameter then it works

> TypeError: invokeMember (deployVerticle) on JavaObject[io.vertx.core.impl.VertxImpl@79a870af (io.vertx.core.impl.VertxImpl)] failed due to: no applicable overload found (overloads: [Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.util.function.Supplier,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.Class,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.util.function.Supplier,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.Class,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)]], arguments: [Test (String), DynamicObject<JSUserObject>@21e85b40 (DynamicObjectBasic), DynamicObject<JSFunction>@1e688567 (DynamicObjectBasic)])
> 	at <js> :anonymous(/Users/chengen/Downloads/verticle.js:31:881-939)
> 	at <js> _load(file:/Users/chengen/Downloads/social4x-1.0-SNAPSHOT.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
> 	at <js> runMain(file:/Users/chengen/Downloads/social4x-1.0-SNAPSHOT.jar!/io/reactiverse/es4x/jvm-npm.js:110:3648-3692)
> 	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:459)
> 	at io.reactiverse.es4x.impl.JSVerticleFactory$1.start(JSVerticleFactory.java:81)
> 	at io.vertx.core.Verticle.start(Verticle.java:66)
> 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
> 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Failed in deploying verticle caused by TypeError: invokeMember (deployVerticle) on JavaObject[io.vertx.core.impl.VertxImpl@79a870af (io.vertx.core.impl.VertxImpl)] failed due to: no applicable overload found (overloads: [Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.util.function.Supplier,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.Class,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.util.function.Supplier,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.Class,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)]], arguments: [Test (String), DynamicObject<JSUserObject>@21e85b40 (DynamicObjectBasic), DynamicObject<JSFunction>@1e688567 (DynamicObjectBasic)])
> 	at <js> :anonymous(/Users/chengen/Downloads/verticle.js:31:881-939)
> 	at <js> _load(file:/Users/chengen/Downloads/social4x-1.0-SNAPSHOT.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
> 	at <js> runMain(file:/Users/chengen/Downloads/social4x-1.0-SNAPSHOT.jar!/io/reactiverse/es4x/jvm-npm.js:110:3648-3692)
> 	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:459)
> 	at io.reactiverse.es4x.impl.JSVerticleFactory$1.start(JSVerticleFactory.java:81)
> 	at io.vertx.core.Verticle.start(Verticle.java:66)
> 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
> 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> TypeError: invokeMember (deployVerticle) on JavaObject[io.vertx.core.impl.VertxImpl@79a870af (io.vertx.core.impl.VertxImpl)] failed due to: no applicable overload found (overloads: [Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.String,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.util.function.Supplier,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.Class,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.util.function.Supplier,io.vertx.core.DeploymentOptions)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(io.vertx.core.Verticle,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)], Method[public void io.vertx.core.impl.VertxImpl.deployVerticle(java.lang.Class,io.vertx.core.DeploymentOptions,io.vertx.core.Handler)]], arguments: [Test (String), DynamicObject<JSUserObject>@21e85b40 (DynamicObjectBasic), DynamicObject<JSFunction>@1e688567 (DynamicObjectBasic)])
> 	at <js> :anonymous(/Users/chengen/Downloads/verticle.js:31:881-939)
> 	at <js> _load(file:/Users/chengen/Downloads/social4x-1.0-SNAPSHOT.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
> 	at <js> runMain(file:/Users/chengen/Downloads/social4x-1.0-SNAPSHOT.jar!/io/reactiverse/es4x/jvm-npm.js:110:3648-3692)
> 	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:459)
> 	at io.reactiverse.es4x.impl.JSVerticleFactory$1.start(JSVerticleFactory.java:81)
> 	at io.vertx.core.Verticle.start(Verticle.java:66)
> 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
> 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
> 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by pmlopes** [comment] 2019-11-26 11:21
@chengenzhao it's not related to graal, the issue is that there's no automatic conversion between json and `DataObjects` so graal cannot find the right signature, in order to fix this we need to be strict:

```js
// import { DeploymentOptions } from "@vertx/core/options"
const DeploymentOptions = require('@vertx/core/options');

var options = new DeploymentOptions({
  "instances" : 1
};
console.log(options);
vertx.deployVerticle('regression.Verticle', options);
```

And this will work, an automatic converter would be simple to add if `DataObjects` were not annotations but a marker interface... but that is something that needs to be requested upstream in vert.x core as it will affect every module out there...

**Comment by chengenzhao** [comment] 2019-11-26 15:20
Good Evening Paulo:

We just made some tests, and 

```javascript
import { DeploymentOptions } from '@vertx/core/options'; //works but config json still not pass into the verticle
//const DeploymentOptions = require('@vertx/core/options'); //TypeError: DeploymentOptions is not a constructor

var options = new DeploymentOptions({
  "instance" : 1
});

console.log(options);
vertx.deployVerticle('Test', options, (res, err)=>{
  if(err){
    console.log('error');
  }else{
    console.log('succeed');
  }
});
```

```java
import io.vertx.core.AbstractVerticle;

public class Test extends AbstractVerticle {
  public void start() {
    System.out.println(config());//couldn't get the config json, it is empty here

    vertx.createHttpServer().requestHandler(req -> {
      req.response()
        .putHeader("content-type", "text/plain")
        .end("Hello from Vert.x!");
    }).listen(8080);
  }
}
```

**Comment by chengenzhao** [comment] 2019-11-26 15:22
```text
chengen@Chengens-MBP Downloads % ~/jdk/graalvm-ce-java11-19.3.0/Contents/Home/bin/java -jar social4x-1.0-SNAPSHOT.jar
io.vertx.core.DeploymentOptions@f85571fa
Succeeded in deploying verticle
{} <--------------- config() returns empty json
succeed
```

**Comment by pmlopes** [comment] 2019-11-26 15:28
Sorry, there's a typpo on my side:

```js
const DeploymentOptions = require('@vertx/core/options').DeploymentOptions;
```

**Comment by pmlopes** [comment] 2019-11-26 15:30
Also the `DeploymentOptions` to pass config should be:

```js
new DeploymentOptions().setConfig({ variable: "value" });
```

**Comment by pmlopes** [comment] 2019-11-26 15:30
see the java API, this is exactly the same for JS https://vertx.io/docs/apidocs/io/vertx/core/DeploymentOptions.html

**Comment by chengenzhao** [comment] 2019-11-26 15:35
got it
it works fine now
but based on the doc of vertx.io, json as deploymentOptions should work here
so maybe evaluations of the impact of upstream changes  needs to be done:)

**Comment by pmlopes** [comment] 2019-11-26 15:38
My IDE can give me hints about the API:

![image](https://user-images.githubusercontent.com/849467/69648244-33832800-106b-11ea-8760-40177d96cafe.png)

**Comment by pmlopes** [comment] 2019-11-26 15:39
Which also tells me the the template should be fixed to the reference is correct on the 1st line or things don't work as expected

**Comment by chengenzhao** [comment] 2019-11-26 15:41
Is IDE vsc?

**Comment by chengenzhao** [comment] 2019-11-27 04:31
looks very nice
BTW, is it possible to provide 4.0.0-milestone version ES4X?
becoz without returning promise/future, it is difficult to use await syntax:)

**Comment by chengenzhao** [comment] 2019-11-27 04:32
We have bumped our prod. version of vert.x to 4.0.0-milestone 
although there is some risk which we are happy to take

**Comment by pmlopes** [comment] 2019-11-27 05:54
I've a separate branch for it. Because of the on going changes on future/promise while these things don't settle on vertx core they keep breaking on es4x.

I'll bring the branch up to date soon.

**Comment by chengenzhao** [comment] 2019-11-27 13:54
If we could have one version based on 4.0.0-milestone will be nice
thus we could add es4x in our projects
becoz we have already bump the version to 4.0 and use future/promise return in our code:)

**Comment by pmlopes** [comment] 2019-11-27 14:11
@chengenzhao please continue the discussion on #265 As that is unreleated to this issue and I'll close this one then.

**Closed by pmlopes** 2019-11-27 14:11 UTC
Labels: bug
