### ISSUE TITLE
es4x jlink is not working

### ISSUE THREAD

**Issue by abner** [reactiverse/es4x#230] opened 2019-10-17 11:50 UTC
When running jlink i get this error

```
Linking: Warning: split package: io.vertx.core.json file:///home/abner/projetos/es4x/js-java-app/node_modules/.lib/vertx-core-3.8.2.jar node_modules/.bin/es4x-launcher.jarjava.base,java.compiler,java.desktop,java.naming,java.sql,jdk.unsupported,jdk.internal.vm.ci
Error: Module Warning: split package: io.vertx.core.json file:///home/abner/projetos/es4x/js-java-app/node_modules/.lib/vertx-core-3.8.2.jar node_modules/.bin/es4x-launcher.jarjava.base not found
```
and the jlink command fails.

I actually saw that jdeps is printing the warnning ` Warning: split package: io.vertx.core.json file:///...` and looks like it is messing up with the module list which will be passed through to jlink.

Passing quiet argument `-q` to jdeps would fix this.

**Comment by pmlopes** [comment] 2019-10-18 02:24
Thanks for the report, the issue is related to the "hack" to allow java json types to be seen as js json types automatically... as 2 classes from core are overriden, Perhaps instead of having the overrides on a different jar, they should go on a patcher core jar however this will not work if the jar is signed.

**Comment by pmlopes** [comment] 2019-10-18 11:39
`-q` has been added to `0.9.5` it should work for now until a proper fix is found

**Comment by pmlopes** [comment] 2019-11-22 21:21
0.10.0 released with the fix

**Closed by pmlopes** 2019-11-22 21:21 UTC
Labels: bug
