### ISSUE TITLE
can't start a vert.x server

### ISSUE THREAD

**Issue by catalsdevelop** [reactiverse/es4x#245] opened 2019-11-19 02:39 UTC
First, thanks for the amazing project. When I try to run *hello world*, an error occurred.

my env:
```
$ es4x versions
VM:      OpenJDK 64-Bit Server VM
Vert.x:  3.8.3
ES4X:    0.9.5
graaljs: 19.2.0.1
```

this is the generated package.json (no `dependencies` and `devDependencies` at first, I added them later with `yarn add`)
```
{
  "version": "1.0.0",
  "description": "This is a ES4X empty project.",
  "main": "index.js",
  "scripts": {
    "test": "es4x test index.test.js",
    "postinstall": "es4x install",
    "start": "es4x"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "name": "es4x",
  "dependencies": {
    "@vertx/core": "^3.8.3",
    "@vertx/web": "^3.8.3"
  },
  "devDependencies": {
    "@vertx/unit": "^3.8.3"
  }
}
```

demo code
```
/// <reference types="es4x.d.ts" />
// @ts-check
import { Router } from '@vertx/web';

const app = Router.router(vertx);

app.route('/').handler(ctx => {
  ctx.response()
    .end('Hello from Vert.x Web!');
});

vertx.createHttpServer()
  .requestHandler(app)
  .listen(8080);
  
console.log('Server listening at: http://localhost:8080/')
```

errors when run `yarn start`
```
yarn run v1.19.1
$ es4x
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleOptions.<clinit>(TruffleOptions.java:143)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory$ResolvedDispatch.register(LibraryFactory.java:559)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryExport.register(LibraryExport.java:117)
	at org.graalvm.truffle/com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<clinit>(DynamicDispatchLibrary.java:183)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:437)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:418)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:411)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:162)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:115)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:106)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:437)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:418)
	at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:411)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:1189)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue.<clinit>(PolyglotValue.java:117)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:111)
	at org.graalvm.sdk/org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:202)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:695)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:660)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:660)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.access$000(Engine.java:102)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:111)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine.getImpl(Engine.java:263)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:501)
	at io.reactiverse.es4x.ECMAEngine.<init>(ECMAEngine.java:98)
	at io.reactiverse.es4x.ESVerticleFactory.init(ESVerticleFactory.java:41)
	at io.vertx.core.impl.DeploymentManager.registerVerticleFactory(DeploymentManager.java:321)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at io.vertx.core.impl.DeploymentManager.loadVerticleFactories(DeploymentManager.java:75)
	at io.vertx.core.impl.DeploymentManager.<init>(DeploymentManager.java:70)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:168)
	at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
	at io.vertx.core.Vertx.vertx(Vertx.java:85)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
	at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:278)
	at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.reactiverse.es4x.ES4X.main(ES4X.java:72)
Caused by: java.lang.UnsupportedOperationException: jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.getCompilationLevelAdjustment() is no longer supported. Use jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.excludeFromJVMCICompilation() instead.
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:471)
	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:178)
	at jdk.internal.vm.ci/jdk.vm.ci.runtime.JVMCI.initializeRuntime(Native Method)
	at jdk.internal.vm.ci/jdk.vm.ci.runtime.JVMCI.getRuntime(JVMCI.java:65)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.hotspot.AbstractHotSpotTruffleRuntimeAccess.getRuntime(AbstractHotSpotTruffleRuntimeAccess.java:42)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle$1.run(Truffle.java:187)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle$1.run(Truffle.java:155)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle.initRuntime(Truffle.java:155)
	at org.graalvm.truffle/com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:62)
	... 48 more
java process exited with code 1
✨  Done in 0.84s.
```

I think the key hint is `java.lang.UnsupportedOperationException: jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.getCompilationLevelAdjustment() is no longer supported. Use jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.excludeFromJVMCICompilation() instead.`,  I am not familiar with java or jvm, so I was stunned here.

**Comment by pmlopes** [comment] 2019-11-19 05:42
I need to ask upstream, this is a crash in graalvm where some classes seem not to be compatible.

**Comment by pmlopes** [comment] 2019-11-26 14:41
@catalsdevelop can you tell me what java version your system has?

```
java -version
```

And be sure that if you have a `JAVA_HOME` environmental variable set that the command above is run using it e.g.:

```
$JAVA_HOME/bin/java -version
```

This does look like a miss match between JVM and dependencies...

**Comment by catalsdevelop** [comment] 2019-12-01 00:36
sorry, @pmlopes . It was my fault that didn't install  graalvm before, which I thought it was installed with jdk as default. It works after I install `graalvm-ce-19.2.1`, but still has a polyfill error with `graalvm-ce-java11-19.3.0`.

```
$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-jvmci-19.3-b05-LTS)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 11.0.5+10-jvmci-19.3-b05-LTS, mixed mode, sharing)
```

error:
```
$ yarn start
yarn run v1.19.1
$ es4x
ReferenceError: global is not defined
	at <js> :program(file:/Users/chameleon/work/node/es4x/node_modules/.lib/es4x-0.9.5.jar!/io/reactiverse/es4x/polyfill/global.js:152:3840-3845)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:344)
	at io.reactiverse.es4x.Runtime.<init>(Runtime.java:116)
	at io.reactiverse.es4x.ECMAEngine.newContext(ECMAEngine.java:209)
	at io.reactiverse.es4x.ESVerticleFactory.createRuntime(ESVerticleFactory.java:63)
	at io.reactiverse.es4x.ESVerticleFactory.createVerticle(ESVerticleFactory.java:88)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:243)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:216)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:80)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:183)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:156)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:145)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:681)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:168)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.reactiverse.es4x.ES4X.main(ES4X.java:72)
Failed in deploying verticle caused by ReferenceError: global is not defined
	at <js> :program(file:/Users/chameleon/work/node/es4x/node_modules/.lib/es4x-0.9.5.jar!/io/reactiverse/es4x/polyfill/global.js:152:3840-3845)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:344)
	at io.reactiverse.es4x.Runtime.<init>(Runtime.java:116)
	at io.reactiverse.es4x.ECMAEngine.newContext(ECMAEngine.java:209)
	at io.reactiverse.es4x.ESVerticleFactory.createRuntime(ESVerticleFactory.java:63)
	at io.reactiverse.es4x.ESVerticleFactory.createVerticle(ESVerticleFactory.java:88)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:243)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:216)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:80)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:183)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:156)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:145)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:681)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:168)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.reactiverse.es4x.ES4X.main(ES4X.java:72)
ReferenceError: global is not defined
	at <js> :program(file:/Users/chameleon/work/node/es4x/node_modules/.lib/es4x-0.9.5.jar!/io/reactiverse/es4x/polyfill/global.js:152:3840-3845)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:344)
	at io.reactiverse.es4x.Runtime.<init>(Runtime.java:116)
	at io.reactiverse.es4x.ECMAEngine.newContext(ECMAEngine.java:209)
	at io.reactiverse.es4x.ESVerticleFactory.createRuntime(ESVerticleFactory.java:63)
	at io.reactiverse.es4x.ESVerticleFactory.createVerticle(ESVerticleFactory.java:88)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:243)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:216)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:80)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:183)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:156)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:145)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:681)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:168)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.reactiverse.es4x.ES4X.main(ES4X.java:72)
✨  Done in 1.65s.
```

**Comment by pmlopes** [comment] 2019-12-01 05:45
Hi polyfill errors and grail 19.3 support have been fixed on 0.10.0 release. If you upgrade it should work.

**Comment by catalsdevelop** [comment] 2019-12-02 05:01
Thanks, @pmlopes. Update 0.1.0 and works good !

**Comment by superxp** [comment] 2020-09-24 04:01
**my env:**

D:\code_ls\my-app>es4x versions
VM:      OpenJDK 64-Bit Server VM - 11.0.8
Vert.x:  3.9.3
ES4X:    0.13.0
graaljs: 20.1.0

D:\code_ls\my-app>java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)


**error**

D:\code_ls\my-app>npm start

> my-app@1.0.0 start D:\code_ls\my-app
> es4x

Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.reactiverse.es4x.ECMAEngine.<init>(ECMAEngine.java:181)
        at io.reactiverse.es4x.ESVerticleFactory.init(ESVerticleFactory.java:41)
        at io.vertx.core.impl.DeploymentManager.registerVerticleFactory(DeploymentManager.java:321)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.vertx.core.impl.DeploymentManager.loadVerticleFactories(DeploymentManager.java:75)
        at io.vertx.core.impl.DeploymentManager.<init>(DeploymentManager.java:70)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:170)
        at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
        at io.vertx.core.Vertx.vertx(Vertx.java:85)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
        at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:278)
        at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
        at io.reactiverse.es4x.ES4X.main(ES4X.java:74)
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 9
^\.\|\\.\
        at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1788)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
        at io.reactiverse.es4x.impl.VertxFileSystem.<clinit>(VertxFileSystem.java:43)
        ... 19 more
java
[
  '-XX:+IgnoreUnrecognizedVMOptions',
  '--module-path=node_modules\\.jvmci',
  '-XX:+UnlockExperimentalVMOptions',
  '-XX:+EnableJVMCI',
  '--upgrade-module-path=node_modules\\.jvmci\\compiler.jar',
  '-cp',
  'node_modules\\.bin\\es4x-launcher.jar;C:\\Users\\necho.duan\\AppData\\Roaming\\npm\\node_modules\\es4x-pm\\es4x-pm-0.13.0.jar',
  'io.reactiverse.es4x.ES4X'
]
java process exited with code 1

**Comment by jaivis** [comment] 2020-10-09 21:33
> **my env:**
> 
> D:\code_ls\my-app>es4x versions
> VM: OpenJDK 64-Bit Server VM - 11.0.8
> Vert.x: 3.9.3
> ES4X: 0.13.0
> graaljs: 20.1.0
> 
> D:\code_ls\my-app>java -version
> openjdk version "11.0.8" 2020-07-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
> 
> **error**
> 
> D:\code_ls\my-app>npm start
> 
> > my-app@1.0.0 start D:\code_ls\my-app
> > es4x
> 
> Exception in thread "main" java.lang.ExceptionInInitializerError
> at io.reactiverse.es4x.ECMAEngine.(ECMAEngine.java:181)
> at io.reactiverse.es4x.ESVerticleFactory.init(ESVerticleFactory.java:41)
> at io.vertx.core.impl.DeploymentManager.registerVerticleFactory(DeploymentManager.java:321)
> at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> at io.vertx.core.impl.DeploymentManager.loadVerticleFactories(DeploymentManager.java:75)
> at io.vertx.core.impl.DeploymentManager.(DeploymentManager.java:70)
> at io.vertx.core.impl.VertxImpl.(VertxImpl.java:170)
> at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
> at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
> at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
> at io.vertx.core.Vertx.vertx(Vertx.java:85)
> at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
> at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:278)
> at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
> at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
> at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
> at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
> at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
> at io.reactiverse.es4x.ES4X.main(ES4X.java:74)
> Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 9
> ^.|\.
> at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
> at java.base/java.util.regex.Pattern.compile(Pattern.java:1788)
> at java.base/java.util.regex.Pattern.(Pattern.java:1428)
> at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
> at io.reactiverse.es4x.impl.VertxFileSystem.(VertxFileSystem.java:43)
> ... 19 more
> java
> [
> '-XX:+IgnoreUnrecognizedVMOptions',
> '--module-path=node_modules\.jvmci',
> '-XX:+UnlockExperimentalVMOptions',
> '-XX:+EnableJVMCI',
> '--upgrade-module-path=node_modules\.jvmci\compiler.jar',
> '-cp',
> 'node_modules\.bin\es4x-launcher.jar;C:\Users\necho.duan\AppData\Roaming\npm\node_modules\es4x-pm\es4x-pm-0.13.0.jar',
> 'io.reactiverse.es4x.ES4X'
> ]
> java process exited with code 1

SAME ISSUE FOR ME

**Comment by pmlopes** [comment] 2020-10-10 04:42
I'll investigate, it seems to happen only on Windows.

**Comment by pmlopes** [comment] 2020-10-21 15:18
The detection of relative paths uses a regular expression not compatible with windows

**Closed** 2020-10-23 14:07 UTC
Labels: bug
